org.gradle.jvmargs=-Xmx2048M -Dorg.gradle.java.home=/usr/lib/jvm/java-25-openjdk

minecraft_version=26.1.2
enabled_platforms=fabric

archives_base_name=mundosync
mod_version=1.0.0
maven_group=link.mundosync

architectury_version=4.11.93

fabric_loader_version=0.19.3
fabric_api_version=0.153.0+26.1.2

quic_version=0.0.15
iroh_java_version=0.26.0
dirs_version=1.5
modmenu_version=7.0.0
